### 캐시 뿌리기
POST http://localhost:8080/cash/share
Content-Type: application/json
X-USER-ID: 1234
X-ROOM-ID: ROOM_1234

{
  "shareAmount" : 11,
  "sharePerson" : 2
}
### 뿌리기 결과 조회
GET http://localhost:8080/cash/share/pee
Content-Type: application/json
X-USER-ID: 1234
X-ROOM-ID: ROOM_1234
####

#### 캐시 획득
PUT http://localhost:8080/cash/share/BCD
Content-Type: application/json
X-USER-ID: 2113
X-ROOM-ID: ROOM_1234

####